#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <stdio.h>
#include <fstream>
#include <cmath>
#include <time.h>
#include <string.h>
#include "checkNumber.h"
#include "command1.h"
#include "command2.h"
#include "command3.h"
#include "command4.h"
#include "command5.h"
#include "dataGenerator.h"
#include "writeFile.h"
#include "heapSort.h"
#include "radixSort.h"
#include "mergeSort.h"
#include "shakerSort.h"
#include "quickSort.h"
#include "shellSort.h"
#include "insertionSort.h"
#include "flashSort.h"
#include "countingSort.h"
#include "selectionSort.h"
#include "bubbleSort.h"
using namespace std;
